# ftpserver configuration file
#
# These are all the config parameters with their default values. If not present,
# Max number of control connections to accept
# max_connections = 0
max_connections = 10
[server]
# Address to listen on
# listen_host = "0.0.0.0"
# Port to listen on
listen_port = 2121
# Public host to expose in the passive connection
# public_host = ""
# Idle timeout time
# idle_timeout = 900
# Data port range from 10000 to 15000
# [dataPortRange]
# start = 2122
# end = 2200
[server.dataPortRange]
start = 2122
end = 2200
[[users]]
user="admin"
pass="123456"
dir="shared"
[[users]]
user="test"
pass="test"
dir="shared"
